language: python

python:
  - "3.6"

cache:
  directories:
    - node_modules

before_install:
  - wget https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh -O ~/.nvm/nvm.sh
  - source ~/.nvm/nvm.sh
  - nvm install 12.6.0 # for Node v5
  - node --version
  - sudo pip install awscli # install awscli
  - aws configure set default.s3.signature_version s3v4 configure

install:
  - npm install

script:
  - npm run build
  - aws --endpoint-url https://minio.ymzstudio.com s3 sync dist s3://${TRAVIS_REPO_SLUG}/${$TRAVIS_BRANCH} --delete

branches:
  only:
    - master
    - release
    - dev

notifications:
  webhooks:
    urls:
      - https://open.feishu.cn/officialapp/notify/3058121f3ea9982acefd3382a1ce3934232ccb50b8a239f9d9b2c543934fabad
    on_start: always # default: never
