language: node_js

node_js:
  - "12.6.0"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build

deploy:
  provider: s3
  access_key_id: $MINIO_ACCESS_KEY
  secret_access_key: $MINIO_ACCESS_SECRET
  bucket: pages
  local_dir: dist
  skip_cleanup: true
  acl: public_read
  endpoint: https://minio.ymzstudio.com
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|release|dev)$

notifications:
  webhooks:
    urls:
      - https://open.feishu.cn/officialapp/notify/3058121f3ea9982acefd3382a1ce3934232ccb50b8a239f9d9b2c543934fabad
    on_start: always # default: never
